export const teacherCertificationTable = reactive([
    {
        title: '资格证',
        children: [
          {
            info: '教师资格',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "certificationKind",
                label: "资格证种类",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "authenticationStudying",
                label: "认证学段",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "authenticationSubject",
                label: "认证学科",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "authority",
                label: "颁发机构",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "firstRegisterTime",
                label: "首次注册日期",
                value: "",
                type: "date",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "regularRegisterTime",
                label: "定期注册日期",
                value: "",
                type: "date",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "teacherCertificationID",
                label: "教师资格证号码",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "issuingCertificatesTime",
                label: "证书颁发日期",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "firstRegisterConclusion",
                label: "首次注册结论",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "regularRegisterConclusion",
                label: "定期注册结论",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     certificateCategory: "高级中学",
            //     certificationStage: '大学',
            //     certifiedDiscipline: '高数',
            //     authority: "成都市教育局",
            //     firstRegistrationDate: "2018-06-31",
            //     regularRegistrationDate: "2020-06-31",
            //     certifiedTeacherNo: "11111111122222222",
            //     certificateIssuanceDate: "2018-06-31",
            //     firstRegistrationConclusion: "无",
            //     regularRegistrationConclusion: "无",
            //     // annex: "附件",
            //   }
            ],
          },
          {
            info: '教师资格证认定信息',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop: "certificateState",
                label: "证照状态",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop: "releaseDate",
                label: "证书签发日期",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop: "qualificationKind",
                label: "资格种类",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop: "organizationName",
                label: "认证机构名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop: "affirmBatch",
                label: "认定批次",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop: "certificateId",
                label: "证书编号",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop: "teacherCertificationId",
                label: "教师资格证编号",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     licenseStatus: "证照状态",
            //     certificateIssuanceDate: '证书签发日期',
            //     qualificationType: '资格种类',
            //     certificationBodyName: "认证机构名称",
            //     confirmedBatch: "认定批次",
            //     certificateNo: "证书编号",
            //     certifiedTeacherNo: "教师资格证编号",
            //   }
            ],
          },
          {
            info: '培训学时记录',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "trainStartTime",
                label: "培训开始时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "trainEndTime",
                label: "培训结束时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "trainingHours",
                label: "教师培训学时",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "trainOrganizationName",
                label: "组织培训单位",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     trainingStartTime: "培训开始时间",
            //     trainingEndTime: '培训结束时间',
            //     trainingClassHour: '教师培训学时',
            //     organizationalTrainingUnit: "组织培训单位",
            //   }
            ],
          },
          {
            info: '证书信息',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "certificateType",
                label: "证书类型",
                value: "",
                isMust: true,
                type: "select",
                isDisable: false,
              },
              {
                prop2: "certificateId",
                label: "证书编号",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "languageCertificateName",
                label: "语言证书名称",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "certificateName",
                label: "证书名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getCertificateTime",
                label: "发证年月",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getCertificateUnit",
                label: "发证单位",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     certificateType: "证书类型",
            //     certificateNo: '证书编号',
            //     LanguageCertificateName: '语言证书名称',
            //     certificateName: "组织培训单位",
            //     issuanceTime: "发证年月",
            //     issuanceUnit: "组织培训单位",
            //     // annex: "附件",
            //   }
            ],
          },
          {
            info: '社会体育指导员证书',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "certificateGrade",
                label: "证书等级",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getCertificateTime",
                label: "发证时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "guidanceProject",
                label: "指导项目",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "guidanceSite",
                label: "指导站点",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "certificateId",
                label: "证书编号",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getCertificateUnit",
                label: "发证单位",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     certificateType: "证书类型",
            //     issuanceTime: "发证时间",
            //     GuidingProject: '指导项目',
            //     GuidanceSite: "指导站点",
            //     certificateNo: '证书编号',
            //     issuanceUnit: "发证单位",
            //   }
            ],
          },
          {
            info: '社会体育指导员技术等级培训信息',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "issueUnit",
                label: "发证单位",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "issueTime",
                label: "发证时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "trainScore",
                label: "成绩",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop: "nation",
                label: "民族",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "guidanceProject",
                label: "指导项目",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "certificateId",
                label: "证书编号",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "guidanceSite",
                label: "指导站点",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     issuanceUnit: "发证单位",
            //     issuanceTime: "发证时间",
            //     achievement: "成绩",
            //     nation: "民族",
            //     GuidingProject: '指导项目',
            //     GuidanceSite: "指导站点",
            //     certificateNo: '证书编号',
            //   }
            ],
          },
          {
            info: '等级裁判员信息',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "project",
                label: "项目",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "judgeGrade",
                label: "裁判等级",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "ratifyTime",
                label: "批准日期",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "relationPhone",
                label: "联系手机",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "comment",
                label: "备注",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "receptionTime",
                label: "接收时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     project: "项目",
            //     JudgmentLevel: "裁判等级",
            //     ApprovalDate: "批准日期",
            //     phoneNumber: "联系手机",
            //     notes: '指导项目',
            //     GuidanceSite: "备注",
            //     ReceptionTime: '接收时间',
            //   }
            ],
          },
          {
            info: '国家医药证书',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "nationMedicineCertificateName",
                label: "国家医药证书名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "certificateId",
                label: "证书(批件)号",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "selfRole",
                label: "本人角色",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "ratifyTime",
                label: "颁布或批准时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "inDateTime",
                label: "有效期",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "isRepresentativeAchievement",
                label: "是否是代表性成果和项目",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     NationalMedicalCertificate: "国家医药证书",
            //     CertificateNumber: "证书(批件)号",
            //     MyRole: "本人角色",
            //     ApproveTime: "颁布或批准时间",
            //     expirationDate: '有效期',
            //     isRepresentativeness: "是否是代表性成果和项目",
            //     // annex: '附件',
            //   }
            ],
          },
          {
            info: '国家标准或行业标准',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "standardId",
                label: "标准号",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "selfRole",
                label: "本人角色",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "releaseTime",
                label: "发布日期",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "releaseUnit",
                label: "发布单位",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "isRepresentativeAchievement",
                label: "是否是代表性成果和项目",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     StandardNumber: "标准号",
            //     MyRole: "本人角色",
            //     ApproveTime: "发布日期",
            //     ApproveUnit: '发布单位',
            //     isRepresentativeness: "是否是代表性成果和项目",
            //     // annex: '附件',
            //   }
            ],
          },
          {
            info: '语言能力',
            isOperate: true,
            isBtn: true,
            isAnnex: true,
            tableHeader: [
              {
                prop2: "language",
                label: "语种",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "masteryDegree",
                label: "掌握程度",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     languages: "语种",
            //     MasteryLevel: "掌握程度",
            //   }
            ],
          },
        ]
      },
])