export const studyExperienceTable = reactive([
    {
        title: '学习经历',
        children: [
          {
            info: '学习经历',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "entranceTime",
                label: "入学年月",
                value: "",
                type: "dateMonth",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择入学年月', trigger: 'blur' },
                ],
                time2:"time2",
              },
              {
                prop2: "graduateTime",
                label: "毕业年月",
                value: "",
                type: "dateMonth",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择毕业年月', trigger: 'blur' },
                ],
                time2:"time2",
              },
              {
                prop2: "learningStyle",
                label: "学习方式",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择学习方式', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
              },
              {
                prop2: "unitCategory",
                label: "在学单位类别",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择在学单位类别', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
                
              },
              {
                prop2: "educationBackground",
                label: "学历",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择学历', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
              },
              {
                prop2: "getEducationBackgroundNation",
                label: "获得学历的国家(地区)",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '获得学历的国家(地区)', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
              },
              {
                prop2: "getEducationBackgroundAcademy",
                label: "获得学历的院校或机构",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请输入获得学历的院校或机构', trigger: 'blur' },
                ],
              },
              {
                prop2: "major",
                label: "专业名称",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择专业名称', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
              },
              {
                prop2: "elseMajor",
                label: "其他专业",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请输入其他专业', trigger: 'change' },
                ],
              },
              {
                prop2: "gradation",
                label: "学位层次",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
                opt: [],
                sName: {},
              },
              {
                prop2: "degreeLevel",
                label: "学位名称",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择学位名称', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
              },
              {
                prop2: "getDegreeNation",
                label: "获得学位的国家(地区)",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择获得学位的国家(地区)', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
              },
              {
                prop2: "getEducationBackgroundAcademy",
                label: "获得学位的院校或机构",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请输入获得学位的院校或机构', trigger: 'blur' },
                ],
              },
              {
                prop2: "awardTime",
                label: "学位授予年月",
                value: "",
                type: "dateMonth",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择学位授予年月', trigger: 'blur' },
                ],
                time2:"time2",
              },
              {
                prop2: "isTeacherTraining",
                label: "是否师范类专业",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择是否师范类专业', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
              },
              {
                prop2: "highestEducation",
                label: "最高学历标识",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                // rules: [
                //   { required: true, message: '请选择学习方式', trigger: 'blur' },
                // ],
                // opt: [],
                // sName: {},
              },
              {
                prop2: "firstEducation",
                label: "第一学历标识",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                // rules: [
                //   { required: true, message: '请选择学习方式', trigger: 'blur' },
                // ],
                // opt: [],
                // sName: {},
              },
            ],
            tableContent: [],
          },
          {
            info: '国内培训',
            isOperate: true,
            isBtn: true,
            isAnnex: true,
            tableHeader: [
              {
                prop2: "trainingName",
                label: "培训项目名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请输入培训项目名称', trigger: 'blur' },
                ],
              },
              {
                prop2: "trainingYear",
                label: "培训年度",
                value: "",
                type: "dateYear",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择培训年度', trigger: 'blur' },
                ],
                time3:"time3",
              },
              {
                prop2: "trainingCategory",
                label: "培训类别",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "trainingOrganization",
                label: "培训机构名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请输入培训机构名称', trigger: 'blur' },
                ],
              },
              {
                prop2: "cultivateWay",
                label: "培训方式",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择培训方式', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
              },
              {
                prop2: "period",
                label: "培训获得学时",
                value: "",
                type: "number",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请输入培训获得学时', trigger: 'blur' },
                ],
              },
              {
                prop2: "credit",
                label: "培训获得学分",
                value: "",
                type: "number",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "trainStart",
                label: "培训开始日期",
                value: "",
                type: "date",
                isMust: false,
                isDisable: false,
                time:"time",
              },
              {
                prop2: "trainEnd",
                label: "培训结束日期",
                value: "",
                type: "date",
                isMust: false,
                isDisable: false,
                time:"time",
              },
            ],
            tableContent: [],
          },
          {
            info: '海外研修',
            isOperate: true,
            isBtn: true,
            isAnnex: true,
            tableHeader: [
              {
                prop2: "cultivateYear",
                label: "培训年度",
                value: "",
                type: "dateYear",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择培训年度', trigger: 'blur' },
                ],
                time:"time",
              },
              {
                prop2: "startTime",
                label: "开始日期",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择开始日期', trigger: 'blur' },
                ],
                time:"time",
              },
              {
                prop2: "endTime",
                label: "结束日期",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择结束日期', trigger: 'blur' },
                ],
                time:"time",
              },
              {
                prop2: "area",
                label: "国家(地区)",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请选择国家(地区)', trigger: 'blur' },
                ],
                opt: [],
                sName: {},
              },
              {
                prop2: "organizationName",
                label: "研修(访学)机构名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请输入研修(访学)机构名称', trigger: 'blur' },
                ],
              },
              {
                prop2: "projectName",
                label: "项目名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请输入项目名称', trigger: 'blur' },
                ],
              },
              {
                prop2: "unitName",
                label: "项目组织单位名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
                rules: [
                  { required: true, message: '请输入项目组织单位名称', trigger: 'blur' },
                ],
              },
            ],
            tableContent: [],
          },
        ]
      },
])