export const teachResearchTable = reactive([
    {
        title: '教学科研成果及获奖',
        children: [
          {
            info: '项目（课题）',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "projectType",
                label: "项目类型",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "projectName",
                label: "项目名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "projectRatifyId",
                label: "项目批准号",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "subjectAmbit",
                label: "学科领域",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "expenditureLimit",
                label: "项目经费额度",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "startTime",
                label: "开始年月",
                value: "",
                type: "dateMonth",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "endTime",
                label: "结束年月",
                value: "",
                type: "dateMonth",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "selfRole",
                label: "项目中本人角色",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "selfRanking",
                label: "本人排名",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "entrustUnit",
                label: "项目委托单位",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "projectSource",
                label: "项目来源",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "isRepresentativeAchievement",
                label: "是否是代表性成果和项目",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "workDescribe",
                label: "本人工作描述",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     project: "项目类型",
            //     entryName: '项目名称',
            //     ProjectApprovalNumber: '项目批准号',
            //     DisciplineField: "学科领域",
            //     ProjectFundingLimit: '项目经费额度',
            //     StartingDate: "开始年月",
            //     EndDate: "结束年月",
            //     MyRole: "项目中本人角色",
            //     MyRanking: "本人排名",
            //     ProjectCommissioningUnit: "项目委托单位",
            //     projectSource: "项目来源",
            //     isRepresentativeness: "是否是代表性成果和项目",
            //     MyJobDescription: "本人工作描述",
            //     // getInstitution: "四川师范大学",
            //     // annex: "附件",
            //   }
            ],
          },
          {
            info: '骨干教师情况',
            isOperate: true,
            isBtn: true,
            isAnnex: true,
            tableHeader: [
              {
                prop2: "backboneTeacherType",
                label: "骨干教师类型",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "backboneTeacherRank",
                label: "骨干教师级别",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "backboneTeacherName",
                label: "骨干称号名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getBackboneTeacherTime",
                label: "获得骨干教师称号时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     backboneTeachersLevel: "骨干教师级别",
            //     backboneTeachersTypes: "骨干教师类型",
            //     backboneTeachersName: "骨干称号名称",
            //     getBackboneTeachersTime: "获得骨干教师称号时间",
            //   }
            ],
          },
          {
            info: '指导学生参加获奖',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "getAwardName",
                label: "获奖名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "selfRole",
                label: "本人角色",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getAwardGrade",
                label: "获奖等级",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getAwardRank",
                label: "获奖级别",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getAwardTime",
                label: "获奖年月",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "jobDescription",
                label: "本人承担工作描述",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     AwardName: "获奖名称",
            //     MyRole: "本人角色",
            //     AwardLevel: "获奖等级",
            //     AwardRank: "获奖级别",
            //     AwardDate: "获奖年月",
            //     MyJobDescription: "本人承担工作描述",
            //     // annex: "附件",
            //   }
            ],
          },
          {
            info: '奖励',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "awardCategory",
                label: "奖励类别",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getAwardTime",
                label: "获奖年月",
                value: "",
                type: "dateMonth",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "awardName",
                label: "奖励名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "awardRank",
                label: "奖励级别",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "awardGrade",
                label: "奖励等级",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "awardElseGrade",
                label: "奖励其他等级",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "selfRanking",
                label: "本人排名",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "area",
                label: "授权国家（地区）",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "awardPrizeUnit",
                label: "授奖单位",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              // {
              //   prop2: "attachment",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     RewardCategory: "奖励类别",
            //     AwardDate: "获奖年月",
            //     AwardName: "奖励名称",
            //     AwardLevel: "奖励级别",
            //     AwardRank: "奖励等级",
            //     AwardOtherLevel: "奖励其他等级",
            //     MyLevel: "本人排名",
            //     enablingState: "授权国家（地区）",
            //     AwardingUnit: "授奖单位",
            //     // annex: "附件",
            //   }
            ],
          },
          {
            info: '荣誉称号',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "honorName",
                label: "荣誉称号",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getHonorTime",
                label: "获得称号时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getHonorRank",
                label: "荣誉称号级别",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "signatureUnit",
                label: "签章单位",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     honoraryTitle: "荣誉称号",
            //     getTitleTime: "获得称号时间",
            //     HonoraryTitleLevel: "荣誉称号级别",
            //     SignatureUnit: "签章单位",
            //   }
            ],
          },
          {
            info: '班主任荣誉',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "honorName",
                label: "荣誉名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getAwardTime",
                label: "获奖时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "signatureUnit",
                label: "签章单位",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     HonoraryName: "荣誉名称",
            //     AwardTime: "获奖时间",
            //     SignatureUnit: "签章单位",
            //   }
            ],
          },
          {
            info: '先进班集体荣誉',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "honorClass",
                label: "荣誉班级",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "classCondition",
                label: "班集体情况",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "signatureTime",
                label: "获奖时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "getAwardRank",
                label: "获奖级别",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "signatureUnit",
                label: "签章单位",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     HonoraryClass: "荣誉班级",
            //     ClassSituation: "班集体情况",
            //     AwardTime: "获奖时间",
            //     AwardLevel: "获奖级别",
            //     SignatureUnit: "签章单位",
            //   }
            ],
          },
          {
            info: '入选人才项目',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "talentProjectName",
                label: "入选人才项目名称",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "talentProjectTime",
                label: "入选年份",
                value: "",
                type: "dateYear",
                isMust: true,
                isDisable: false,
              },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     SelectedProjectName: "入选人才项目名称",
            //     SelectedYear: "入选年份",
            //   }
            ],
          },
          {
            info: '著作',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "productionType",
                label: "著作类别",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "productionName",
                label: "著作名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "subjectAmbit",
                label: "学科领域",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "publicationTime",
                label: "出版日期",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "pressName",
                label: "出版社名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "publicationId",
                label: "出版号",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "inProductionSelfRole",
                label: "著作中本人角色",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "wordNumber",
                label: "总字数（字）",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "selfWrite",
                label: "本人撰写字数（字）",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "isRepresentativeAchievement",
                label: "是否是代表性成果和项目",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     workCategory: "著作类别",
            //     workName: "掌握程度",
            //     DisciplineField: "著作名称",
            //     MasteryLevel: "学科领域",
            //     PublicationDate: "出版日期",
            //     pressName: "出版社名称",
            //     pressNo: "出版号",
            //     workMyRole: "著作中本人角色",
            //     TotalWord: "总字数（字）",
            //     writeWord: "本人撰写字数（字）",
            //     isRepresentativeness: "是否是代表性成果和项目",
            //     // annex: "附件",
            //   }
            ],
          },
          {
            info: '论文案例',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "paperCaseName",
                label: "论文案例名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "paperCaseRank",
                label: "论文案例级别",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "issueJournalsName",
                label: "发表刊物名称",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "issueJournalsRank",
                label: "发表刊物级别",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "isCoreJournal",
                label: "是否核心期刊",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "coreJournalType",
                label: "核心期刊类别",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "publishTime",
                label: "发表年月",
                value: "",
                type: "dateMonth",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "reelId",
                label: "卷号",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "expectId",
                label: "期号",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "startPage",
                label: "起始页码",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "endPage",
                label: "结束页码",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "selfRole",
                label: "本人角色",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "ambit",
                label: "学科领域",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "publicationId",
                label: "论文案例收录情况",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "isPublic",
                label: "是否发表",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "isGetAward",
                label: "是否获奖",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "getAwardTime",
                label: "获奖年月",
                value: "",
                type: "dateMonth",
                isMust: false,
                isDisable: false,
              },
              {
                prop: "awardPrizeUnit",
                label: "授奖单位",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop: "awardName",
                label: "奖励名称",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "isRepresentativeAchievement",
                label: "是否是代表性成果和项目",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              {
                prop: "awardGrade",
                label: "奖励等级",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     PaperCaseName: "论文案例名称",
            //     PaperCaseLevel: "论文案例级别",
            //     PublicationName: "发表刊物名称",
            //     PublicationLevel: "发表刊物级别",
            //     isCoreJournal: "是否核心期刊",
            //     CoreJournalCategories: "核心期刊类别",
            //     publicationDate: "发表年月",
            //     VolumeNumber: "卷号",
            //     ISSUE: "期号",
            //     StartingPage: "起始页码",
            //     EndPage: "结束页码",
            //     myRole: "本人角色",
            //     DisciplineField: "学科领域",
            //     paperEmploy: "论文案例收录情况",
            //     isPublish: "是否发表",
            //     isAwards: "是否获奖",
            //     AwardDate: "获奖年月",
            //     AwardingUnit: "授奖单位",
            //     RewardName: "奖励名称",
            //     isRepresentativeness: "是否是代表性成果和项目",
            //     RewardLevel: "奖励等级",
            //     // annex: "附件",
            //   }
            ],
          },
          {
            info: '文艺作品',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "literaryWorksType",
                label: "文艺作品类别",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "literaryWorksName",
                label: "文艺作品名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "selfRole",
                label: "本人角色",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop: "accomplishTime",
                label: "完成时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "accomplishPlace",
                label: "完成地点",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "workDescribe",
                label: "本人工作描述",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "isRepresentativeAchievement",
                label: "是否是代表性成果和项目",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     literatureType: "文艺作品类别",
            //     literatureName: "文艺作品名称",
            //     myRole: "本人角色",
            //     CompletionTime: "完成时间",
            //     CompletionLocation: "完成地点",
            //     MyJobDescription: "本人工作描述",
            //     isRepresentativeness: "是否是代表性成果和项目",
            //     // annex: "附件",
            //   }
            ],
          },
          {
            info: '专利或软件著作权',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "patentType",
                label: "专利或软件著作权类型",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "patentName",
                label: "专利或软件著作权名称",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "subjectAmbit",
                label: "学科领域",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "ratifyTime",
                label: "批准日期",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "selfRole",
                label: "本人角色",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "workDescribe",
                label: "本人工作描述",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "isRepresentativeAchievement",
                label: "是否是代表性成果和项目",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     PatentType: "专利或软件著作权类型",
            //     PatentName: "专利或软件著作权名称",
            //     DisciplineField: "掌握程度",
            //     ApprovalDate: "批准日期",
            //     myRole: "本人角色",
            //     MyJobDescription: "本人工作描述",
            //     isRepresentativeness: "是否是代表性成果和项目",
            //     // annex: "附件",
            //   }
            ],
          },
          {
            info: '咨询报告或研究报告',
            isOperate: true,
            isAnnex: true,
            isBtn: true,
            tableHeader: [
              {
                prop2: "reportTitle",
                label: "报告题目",
                value: "",
                type: "input",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "selfRole",
                label: "本人角色",
                value: "",
                type: "select",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "reportTime",
                label: "报告时间",
                value: "",
                type: "date",
                isMust: true,
                isDisable: false,
              },
              {
                prop2: "client",
                label: "委托方",
                value: "",
                type: "input",
                isMust: false,
                isDisable: false,
              },
              {
                prop2: "isRepresentativeAchievement",
                label: "是否是代表性成果和项目",
                value: "",
                type: "select",
                isMust: false,
                isDisable: false,
              },
              // {
              //   prop: "annex",
              //   label: "附件",
              // },
            ],
            tableContent: [
            //   {
            //     id: 0,
            //     ReportTitle: "报告题目",
            //     myRole: "本人角色",
            //     ReportTime: "报告时间",
            //     client: "委托方",
            //     isRepresentativeness: "是否是代表性成果和项目",
            //     // annex: "附件",
            //   }
            ],
          },
        ]
      },
])