 export const educationAndTraining = ref({
      title: '师德信息',
      children: [
        {
          info: '师德考核',
          isOperate: true,
          isBtn: true,
          isAnnex: true,
          allPage:0,
          tableHeader: [
            {
              width: "136px",
              prop2: "teacherMeritAssessTime",
              label: "师德考核时间",
              new:'top',
              value: "",
              type: "dateYear",
              isMust: true,
              isDisable: false,
              rules: [
                { required: true, message: '请选择师德考核时间', trigger: 'change' },
              ],
            },
            {
              width: "136px",
              prop2: "teacherMeritAssessResult",
              label: "师德考核结论",
              value: "",
              type: "select",
              isMust: true,
              isDisable: false,
            },
            {
              width: "136px",
              prop2: "teacherMeritAssessUnitName",
              label: "师德考核单位名称",
              value: "",
              type: "input",
              isMust: true,
              isDisable: false,
              rules: [
                { required: true, message: '请输入师德考核单位名称', trigger: 'change' },
              ],
            },
            {
              width: "136px",
              prop2: "recordHonorDescription",
              label: "荣誉记录描述",
              value: "",
              type: "input",
              isMust: true,
              isDisable: false,
            },
            {
              width: "136px",
              prop2: "honorHappenTime",
              label: "荣誉发生日期",
              value: "",
              type: "date",
              isMust: false,
              isDisable: false,
            },
            {
              width: "136px",
              prop2: "honorRank",
              label: "荣誉级别",
              value: "",
              type: "select",
              isMust: false,
              isDisable: false,
            },
            {
              width: "136px",
              prop2: "conferUnitName",
              label: "荣誉授予单位名称",
              value: "",
              type: "input",
              isMust: false,
              isDisable: false,
            },
            {
              width: "136px",
              prop2: "honoraryTitle",
              label: "获得荣誉称号",
              value: "",
              type: "input",
              isMust: false,
              isDisable: false,
            },
          ],
          tableContent: [
          ],
        },
        {
          info: '处分信息',
          isOperate: true,
          isAnnex: true,
          isBtn: true,
          allPage:0,
          tableHeader: [
            {
              width: "80px",
              prop2: "disciplinaryInformationType",
              label: "处分类型",
              new:'top',
              value: "",
              type: "select",
              isMust: true,
              isDisable: false,
            },
            {
              width: "80px",
              prop2: "deregulationContent",
              label: "违规内容",
              value: "",
              type: "input",
              isMust: true,
              isDisable: false,
              rules: [
                { required: true, message: '请输入违规内容', trigger: 'change' },
              ],
            },
            {
              width: "80px",
              prop2: "notificationTime",
              label: "通报时间",
              value: "",
              type: "date",
              isMust: true,
              isDisable: false,
              rules: [
                { required: true, message: '请选择报告时间', trigger: 'change' },
              ],
            },
            {
              width: "80px",
              prop2: "reportingUnit",
              label: "通报单位",
              value: "",
              type: "input",
              isMust: true,
              isDisable: false,
              rules: [
                { required: true, message: '请输入通报单位', trigger: 'change' },
              ],
            },

          ],
          tableContent: [
          ],
        },
      ]
    }) 